### ISSUE TITLE
Pensar em padrão para realizar persistência das classes de domínio

### ISSUE THREAD

**Issue by paulossa** [paulossa/les20162#4]
1- Ao criar uma atividade/tempoInvestido/User como fazer a persistência desses objetos? 

------ 
1- Usando singleton para um DBManager e utilizando quando necessário.
2- Deixando dentro do objeto e apenas utilizando métodos [save(), update()] nos objetos para que a código de persistência não fique espalhado ao redor da aplicação. 

3- Singleton para o código DBManager + Interface Persistivel [save(), update(), delete()] ???

**Comment by andremilk** [comment]
Nao entendo de android, nao tem nada nesse sentido fornecido pelo google?
Ou talvez alguma solucao gratuita pra isso.. que a gente possa aliar autenticacao e alguma persistencia de dados do usuario tambem

**Comment by erickrdgs** [comment]
A segunda opção me pareceu a melhor, mas minha familiaridade com o Android não é tão grande
